services:
  scraping-backend:
    image: amazon-scraping-backend:latest
    build:
      context: ./src
    ports:
      - "8000:8000"
    environment:
      - POSTGRESQL_CONN_STR=${POSTGRESQL_CONN_STR:-postgresql://admin:123@postgres:5432/postgres}
    ipc: host  # This sets the IPC mode
    security_opt:
      - seccomp=./src/seccomp_profile.json  # This specifies the seccomp profile

    command: python3 main.py api

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  postgres-admin:
    image: dpage/pgadmin4:8
    container_name: postgres-admin
    ports:
      - "2345:2345"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ok.nvm
      - PGADMIN_DEFAULT_PASSWORD=123
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=2345
      - PGADMIN_CONFIG_LOGIN_BANNER="Postgres Admin dashboard"
