services:
  scraper-api:
    image: amazon-scraper-api:latest
    build:
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - RUN_BACKGROUND_TASKS=${RUN_BACKGROUND_TASKS:-0}
    env_file:
      - api/.env
    ipc: host  # This sets the IPC mode
    security_opt:
      - seccomp=./shared/seccomp_profile.json  # This specifies the seccomp profile

    command: python3 main.py

