base_headers = {
    "accept": "text/html,ajax/ajax,*/*",
    "accept-language": "en-US,en;q=0.9,fr;q=0.8",
    "content-type": "application/json",
    "device-memory": "8",
    "downlink": "10",
    "dpr": "0.9375",
    "ect": "4g",
    "priority": "u=1, i",
    "rtt": "100",
    "sec-ch-device-memory": "8",
    "sec-ch-dpr": "0.9375",
    "sec-ch-ua": '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-ch-ua-platform-version": '"15.0.0"',
    "sec-ch-viewport-width": "1261",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "viewport-width": "1261",
}
